### ISSUE TITLE
Python errors when running

### ISSUE THREAD

**Issue by ericpoe** [phpcommunity/docker-hovercraft#1]
Pulled down a fresh image and get the following when trying to serve up `php-testfest-intro.rst`

```bash
Serving HTTP on 0.0.0.0 port 9000 ...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/hovercraft/__init__.py", line 42, in generate_and_observe
    monitor_list = generate(args)
  File "/usr/local/lib/python3.6/site-packages/hovercraft/generate.py", line 135, in generate
    template_info = Template(args.template)
  File "/usr/local/lib/python3.6/site-packages/hovercraft/template.py", line 58, in __init__
    self._load_template_config()
  File "/usr/local/lib/python3.6/site-packages/hovercraft/template.py", line 81, in _load_template_config
    self.config = config['hovercraft']
  File "/usr/local/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'hovercraft'
```

**Comment by ramsey** [comment]
How are you trying to run the container?

**Comment by ericpoe** [comment]
Argh. nm. I found the problem is with `realpath` from the `present` script not being native in OSX. I'll submit a PR for that in the phptestfest repo.

**Comment by ramsey** [comment]
Interesting. I use the `present` script on OSX, and I haven't had that problem. What directory were you in when you ran it?

**Comment by ericpoe** [comment]
I was in the slides directory. I had replaced the `realpath` in the script with `pwd` and it threw the errors once it launched the docker image. A better fix is in https://github.com/phpcommunity/phptestfest.org/pull/54
